### PR TITLE
Solution that actually works

### PR DESCRIPTION
**Pull request by matq007**
This PR is a mixture of @szilvajuhos repository and my experiments. The current solution is set so it can run singularity and slurm together. For that, 2 new profiles were introduced:
1. `uppmax-martin.config`: personal profile for running the pipeline with slurm only
2. `singularity.config`: profile for running pipeline using singularity

I've also created Dockerfile (can be found also on [DockerHub](https://hub.docker.com/r/mproksik/ngi-rna-fusion/)) which is a combination of bare install and conda. There was a suggestion to convert the `fusioncatcher` to conda. I can look into that, but something tells me this is a rabbit hole. 

Lastly, I've included 2 test files that return fusion `BCAS4-BCAS3`.

**Current problems**:
In order for `FusionInspector` to work it requires special format of fusions genes (see [here](https://github.com/FusionInspector/FusionInspector/wiki#running-fusioninspector)) which are generated by `fusion_genes_compare.py` that doesn't work really.

Comments are welcome, merge will be appriciated ⚡️

### CODE REVIEW

**Comment by matq007** [comment]
I can't request reviewers in PR, so comment it is: @ewels, @szilvajuhos and @MaxUlysse

**Comment by ewels** [comment]
Ok nice! Note that the intention is to make this a nf-core pipeline so it would be good to bear that in mind from the start. Specifically:

* We have a repo to host test data already (better than relying on UPPMAX)
* Conda would be really best if possible, if it's a no-go then that's ok though
* We talked about creating a new pipeline from scratch with the template and moving stuff over to that - probably easier to do that sooner rather than later.

See the nf-core developer docs and guidelines here: http://nf-co.re/developer_docs

Having said all this - really nice work :) We can certainly review and merge this PR in isolation first before doing the above stuff and moving the pipeline to nf-core and archiving this repo. Just wanted to flag this before you invest too much time into stuff that will need updating...

Phil

**Comment by maxulysse** [comment]
Looks very nice.
> We have a repo to host test data already (better than relying on UPPMAX)

At the moment the new test data is in the PR, but will be included in the [nf-core/test-datasets repo](https://github.com/nf-core/test-datasets/).

> Conda would be really best if possible, if it's a no-go then that's ok though

Totally agree.

> We talked about creating a new pipeline from scratch with the template and moving stuff over to that - probably easier to do that sooner rather than later.

I asked Martin to make Travis testing before moving stuff over, but we are keeping all that in mind.

**Review by szilvajuhos — APPROVED** [review]
Cool, the whole point is to understand what all these beasts wants to have in place.

**Comment by maxulysse** [comment]
Should we merge that for now then?

**Comment by Hammarn** [comment]
It's a bit odd to have a personal configuration file with hard coded paths in a repo that's ment to be publically avialable/used. That's my only caveat against this. But do what you want ¯\\_(ツ)_/¯

**Comment by ewels** [comment]
Agreed. This and many other things will be resolved in later work though - plan is to move this over to nf-core where we will be much stricter 😉

**Pull request merged**
